package com.example.trace.service;

import com.example.trace.entity.*;
import com.example.trace.enums.DeviceStatus;
import com.example.trace.enums.EventType;
import com.example.trace.repo.*;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.LocalDateTime;
import java.util.*;

@Service
@RequiredArgsConstructor
public class BusinessService {
    private final DeviceRepo deviceRepo;
    private final PurchaseOrderRepo purchaseRepo;
    private final BorrowOrderRepo borrowRepo;
    private final FlowRecordRepo flowRepo;
    private final ChainService chain;

    public List<Device> devices() { return deviceRepo.findAll(); }
    public Optional<Device> device(String code) { return deviceRepo.findByDeviceCode(code); }
    public List<FlowRecord> flows(String code) { return flowRepo.findByDeviceCodeOrderByOperateTimeAsc(code); }
    public List<FlowRecord> allFlows() { return flowRepo.findAll(); }

    @Transactional public Device register(Device d, String operator){ if(deviceRepo.findByDeviceCode(d.getDeviceCode()).isPresent()) throw new RuntimeException("deviceCode already exists"); d.setStatus(DeviceStatus.PRODUCED); d.setCreatedAt(LocalDateTime.now()); d.setUpdatedAt(LocalDateTime.now()); var saved=deviceRepo.save(d); flow(saved,EventType.DEVICE_REGISTER,null,null,String.valueOf(saved.getDeviceId()),"DEVICE",operator,"register"); return saved; }
    @Transactional public PurchaseOrder purchaseApply(Long deviceId, Long hospitalId, String hospitalName, String operator){ Device dv=deviceRepo.findById(deviceId).orElseThrow(); PurchaseOrder p=new PurchaseOrder(); p.setDeviceId(deviceId); p.setDeviceCode(dv.getDeviceCode()); p.setSupplierId(dv.getSupplierId()); p.setSupplierName(dv.getSupplierName()); p.setHospitalId(hospitalId); p.setHospitalName(hospitalName); p.setStatus("PURCHASE_APPLIED"); p.setApplyTime(LocalDateTime.now()); var saved=purchaseRepo.save(p); flow(dv,dv.getCurrentHolderOrgId(),hospitalId,EventType.PURCHASE_APPLY,String.valueOf(saved.getOrderId()),"PURCHASE",operator,"apply"); return saved; }
    @Transactional public PurchaseOrder purchaseApprove(Long orderId, boolean pass, String operator){ PurchaseOrder p=purchaseRepo.findById(orderId).orElseThrow(); if(!"PURCHASE_APPLIED".equals(p.getStatus())) throw new RuntimeException("invalid status"); p.setStatus(pass?"PURCHASE_APPROVED":"PURCHASE_REJECTED"); p.setApproveTime(LocalDateTime.now()); var saved=purchaseRepo.save(p); Device dv=deviceRepo.findById(p.getDeviceId()).orElseThrow(); flow(dv,dv.getSupplierId(),p.getHospitalId(),pass?EventType.PURCHASE_APPROVE:EventType.PURCHASE_REJECT,String.valueOf(orderId),"PURCHASE",operator,saved.getStatus()); return saved; }
    @Transactional public PurchaseOrder purchaseReceive(Long orderId, String operator){ PurchaseOrder p=purchaseRepo.findById(orderId).orElseThrow(); if(!"PURCHASE_APPROVED".equals(p.getStatus())) throw new RuntimeException("must approve first"); p.setStatus("PURCHASE_RECEIVED"); p.setReceiveTime(LocalDateTime.now()); Device d=deviceRepo.findById(p.getDeviceId()).orElseThrow(); d.setCurrentOwnerOrgId(p.getHospitalId()); d.setCurrentOwnerOrgName(p.getHospitalName()); d.setCurrentHolderOrgId(p.getHospitalId()); d.setCurrentHolderOrgName(p.getHospitalName()); d.setStatus(DeviceStatus.IN_STOCK); d.setUpdatedAt(LocalDateTime.now()); deviceRepo.save(d); flow(d,d.getSupplierId(),p.getHospitalId(),EventType.PURCHASE_RECEIVE,String.valueOf(orderId),"PURCHASE",operator,"receive"); return purchaseRepo.save(p); }

    @Transactional public BorrowOrder borrowApply(Map<String,String> req){ Device d=deviceRepo.findById(Long.valueOf(req.get("deviceId"))).orElseThrow(); if(d.getStatus()==DeviceStatus.BORROWED) throw new RuntimeException("device borrowed"); BorrowOrder b=new BorrowOrder(); b.setDeviceId(d.getDeviceId()); b.setDeviceCode(d.getDeviceCode()); b.setLenderHospitalId(Long.valueOf(req.get("lenderHospitalId"))); b.setLenderHospitalName(req.get("lenderHospitalName")); b.setBorrowerHospitalId(Long.valueOf(req.get("borrowerHospitalId"))); b.setBorrowerHospitalName(req.get("borrowerHospitalName")); b.setReason(req.getOrDefault("reason","borrow")); b.setStatus("BORROW_APPLIED"); b.setApplyTime(LocalDateTime.now()); var saved=borrowRepo.save(b); d.setStatus(DeviceStatus.BORROW_APPLYING); deviceRepo.save(d); flow(d,b.getBorrowerHospitalId(),b.getLenderHospitalId(),EventType.BORROW_APPLY,String.valueOf(saved.getBorrowId()),"BORROW",req.getOrDefault("operator","hospital"),"borrow apply"); return saved; }
    @Transactional public BorrowOrder borrowApprove(Map<String,String> req, boolean pass){ BorrowOrder b=borrowRepo.findById(Long.valueOf(req.get("borrowId"))).orElseThrow(); if(!"BORROW_APPLIED".equals(b.getStatus())) throw new RuntimeException("invalid status"); b.setStatus(pass?"BORROW_APPROVED":"BORROW_REJECTED"); b.setApproveTime(LocalDateTime.now()); Device d=deviceRepo.findById(b.getDeviceId()).orElseThrow(); d.setStatus(pass?DeviceStatus.BORROW_APPLYING:DeviceStatus.IN_STOCK); deviceRepo.save(d); flow(d,b.getLenderHospitalId(),b.getBorrowerHospitalId(),pass?EventType.BORROW_APPROVE:EventType.BORROW_REJECT,String.valueOf(b.getBorrowId()),"BORROW",req.getOrDefault("operator","hospital"),b.getStatus()); return borrowRepo.save(b); }
    @Transactional public BorrowOrder borrowLend(Map<String,String> req){ BorrowOrder b=borrowRepo.findById(Long.valueOf(req.get("borrowId"))).orElseThrow(); if(!"BORROW_APPROVED".equals(b.getStatus())) throw new RuntimeException("must approve first"); b.setStatus("LENT_OUT"); b.setLendTime(LocalDateTime.now()); Device d=deviceRepo.findById(b.getDeviceId()).orElseThrow(); d.setStatus(DeviceStatus.BORROWED); d.setCurrentHolderOrgId(b.getBorrowerHospitalId()); d.setCurrentHolderOrgName(b.getBorrowerHospitalName()); deviceRepo.save(d); flow(d,b.getLenderHospitalId(),b.getBorrowerHospitalId(),EventType.DEVICE_LEND_OUT,String.valueOf(b.getBorrowId()),"BORROW",req.getOrDefault("operator","hospital"),"lend out"); return borrowRepo.save(b); }
    @Transactional public BorrowOrder borrowReceive(Map<String,String> req){ BorrowOrder b=borrowRepo.findById(Long.valueOf(req.get("borrowId"))).orElseThrow(); if(!"LENT_OUT".equals(b.getStatus())) throw new RuntimeException("must lend first"); b.setStatus("BORROW_RECEIVED"); b.setReceiveTime(LocalDateTime.now()); Device d=deviceRepo.findById(b.getDeviceId()).orElseThrow(); flow(d,b.getLenderHospitalId(),b.getBorrowerHospitalId(),EventType.BORROW_RECEIVE,String.valueOf(b.getBorrowId()),"BORROW",req.getOrDefault("operator","hospital"),"receive"); return borrowRepo.save(b); }
    @Transactional public BorrowOrder returnApply(Map<String,String> req){ BorrowOrder b=borrowRepo.findById(Long.valueOf(req.get("borrowId"))).orElseThrow(); if(!"BORROW_RECEIVED".equals(b.getStatus())) throw new RuntimeException("must receive first"); b.setStatus("RETURN_APPLIED"); b.setReturnApplyTime(LocalDateTime.now()); Device d=deviceRepo.findById(b.getDeviceId()).orElseThrow(); d.setStatus(DeviceStatus.RETURNING); deviceRepo.save(d); flow(d,b.getBorrowerHospitalId(),b.getLenderHospitalId(),EventType.RETURN_APPLY,String.valueOf(b.getBorrowId()),"BORROW",req.getOrDefault("operator","hospital"),"return apply"); return borrowRepo.save(b); }
    @Transactional public BorrowOrder returnConfirm(Map<String,String> req){ BorrowOrder b=borrowRepo.findById(Long.valueOf(req.get("borrowId"))).orElseThrow(); if(!"RETURN_APPLIED".equals(b.getStatus())) throw new RuntimeException("must apply return first"); b.setStatus("RETURN_CONFIRMED"); b.setReturnConfirmTime(LocalDateTime.now()); Device d=deviceRepo.findById(b.getDeviceId()).orElseThrow(); d.setStatus(DeviceStatus.RETURNED); d.setCurrentHolderOrgId(b.getLenderHospitalId()); d.setCurrentHolderOrgName(b.getLenderHospitalName()); deviceRepo.save(d); flow(d,b.getBorrowerHospitalId(),b.getLenderHospitalId(),EventType.RETURN_CONFIRM,String.valueOf(b.getBorrowId()),"BORROW",req.getOrDefault("operator","hospital"),"return confirmed"); return borrowRepo.save(b); }

    public Map<String,Object> verify(Long flowId){ FlowRecord f=flowRepo.findById(flowId).orElseThrow(); return Map.of("flowId",flowId,"verifyStatus",f.getVerifyStatus(),"dataHash",f.getDataHash(),"txHash",f.getTxHash()); }
    public Map<String,Object> stats(){ long total=deviceRepo.count(); long stock=deviceRepo.findAll().stream().filter(d->d.getStatus()==DeviceStatus.IN_STOCK).count(); long borrowed=deviceRepo.findAll().stream().filter(d->d.getStatus()==DeviceStatus.BORROWED).count(); return Map.of("deviceTotal",total,"inStock",stock,"borrowed",borrowed,"todayFlows",flowRepo.findAll().size()); }

    private void flow(Device d, Long fromOrgId, Long toOrgId, EventType e, String bizId, String bizType, String operator, String remark){ try {String payload=d.getDeviceCode()+"|"+e+"|"+fromOrgId+"|"+toOrgId+"|"+bizId+"|"+operator; String hash=sha(payload); var r=chain.addFlowRecord(d.getDeviceCode(),e.name(),hash,operator); FlowRecord f=new FlowRecord(); f.setDeviceId(d.getDeviceId()); f.setDeviceCode(d.getDeviceCode()); f.setEventType(e.name()); f.setFromOrgId(fromOrgId); f.setToOrgId(toOrgId); f.setOperator(operator); f.setOperateTime(LocalDateTime.now()); f.setBusinessId(bizId); f.setBusinessType(bizType); f.setRemark(remark); f.setDataHash(hash); f.setTxHash((String)r.get("txHash")); f.setChainStatus((String)r.get("chainStatus")); f.setBlockNumber((Long)r.get("blockNumber")); f.setVerifyStatus("PASS"); flowRepo.save(f);} catch(Exception ex){ throw new RuntimeException(ex);} }
    private static String sha(String v) throws Exception { var md=MessageDigest.getInstance("SHA-256"); byte[] b=md.digest(v.getBytes(StandardCharsets.UTF_8)); StringBuilder sb=new StringBuilder("0x"); for(byte c:b) sb.append(String.format("%02x",c)); return sb.toString(); }
}
